<?php
session_start();
//if(!isset($_SESSION['username'])){
//    include "nav.php";
//}
//else{
//    include "nav1.php";
//}
?>

<!DOCTYPE html>
<html lang="zxx">

<head>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<style>
    
    .stars {

  width: 270px;
        margin-left: 131px;
        margin-right: auto;

  display: inline-block;

}

 

input.star { display: none; }

 

label.star {

  float: right;

  padding: 10px;

  font-size: 36px;

  color: #444;

  transition: all .2s;

}

 

input.star:checked ~ label.star:before {

  content: '\f005';

  color: #FD4;

  transition: all .25s;

}

 

input.star-5:checked ~ label.star:before {

  color: #FE7;

  text-shadow: 0 0 20px #952;

}

 

input.star-1:checked ~ label.star:before { color: #F62; }

 

label.star:hover { transform: rotate(-15deg) scale(1.3); }

 

label.star:before {

  content: '\f006';

  font-family: FontAwesome;

}
.checked {
  color: orange;
  size: 5px;
}

        .donate {
border-radius: 20px;
 margin-top: 52px;
 margin-left: 38px;
     margin-right: 38px;
    padding: 9px 18px;
    background: #ffad00;
    border: 3px solid black;
    text-decoration: none;
    color: black;
    letter-spacing: 1px;
    display: inline-block;
    
 }
         .donate:focus {
  border-radius: 20px;
         margin-top: 52px;
 margin-left: 38px;
     margin-right: 38px;
    padding: 9px 18px;
    background: #ffad00;
    border: 3px solid black;
    text-decoration: none;
    color: black;
    letter-spacing: 1px;
    display: inline-block;
   
}
    .donate:hover{
        color: black;
/*        text-decoration: none;*/
    }
        h3.w3l-agile:before {
    content: '';
    background: black;
    height: 1px;
    width: 11%;
    position: absolute;
    bottom: 0%;
    left: 44%;
}
    
     #rate {
     border-radius: 20px;
        
    padding: 9px 18px;
    background: #ffad00;
    border: 3px solid black;
    text-decoration: none;
    color: black;
    letter-spacing: 1px;
    display: inline-block;
    
 }
    .navbar > .container .navbar-brand, .navbar > .container-fluid .navbar-brand {
    height: 118px;
    margin-left: -15px;
}
    img.img-responsive {
    display: block;
    max-width: 100%;
    height: 288px;
}
  
    .col-md-6 {
    margin-right: 52px;
    margin-left: 52px;
    width: 40%;
    margin-top: -26px;
}
  div.title-agileits h3:after {
    content: '';
    background: #ffad00;
    height: 4px;
    width: 0%;
    position:relative;
    bottom: -1px;
    left: 450px;
}
    div.title-agileits h3:after {
    content: '';
    background: #ffad00;
    height: 4px;
    width: 0%;
    position:relative;
    bottom: -1px;
    left: 450px;
    margin-bottom: 9px;
}
     h3.w3l-agile:before {
    content: '';
    background:  #ffad00;
    height: 5px;
    width: 12%;
    position: absolute;
    margin-top: 50px;
    left: 44%;
    margin-bottom: 9px;
}
   p.para{
	margin:0;
    margin-top: 30px;
	    font-family: 'Lato', sans-serif;
    font-size: 18px;
} 
    </style>
    
	<title>The Food Doofs</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="" />
	<link href="https://components.staticcodes.io/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
     <link rel="stylesheet" href="css/abc.css">

</head>
    
<?php
//session_start();
if(!isset($_SESSION['uid'])){
    include "nav.php";
}
else{
    include "nav1.php";
}
?>

<?php
$id = $_GET['restid'];

// echo "Category ".$text." selected<br>";
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://developers.zomato.com/api/v2.1/restaurant?res_id=".$id);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
$headers = array(
  "Accept: application/json",
  "User-Key: 15039fe16c062259656c9a018dc0dc86"
  );
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
$zomdata = json_decode($result);
    
if ($zomdata->thumb != "") {
//      echo "<img width='330' src='".@$restaurant->restaurant->thumb."' class='rest_image' /><br/>";
}else{
        $zomdata->thumb = "images/abc.jpg";
}

?>
    
<body>
    
	<div class="process-agileits">
		<div class="container">
			<div class="title-agileits">
				<h3 class="w3l-agile"><?php echo $zomdata->name;?></h3>
			</div>

			<div class="process_grids">
				<div class="col-md-6 process_left">
					<div class="port-2 effect-1">
						<div class="image-box">
							<img class="img-responsive" src="<?php echo $zomdata->thumb; ?>" width="100%" alt="Image-1">
							
						</div>
						
					</div>
				</div>
<!--                <div class="col-md-6 process_right">-->
							
							<p class="para">
                                <?php echo $zomdata->location->address; echo '<br>' ?>
                                User Rating: <?php echo $zomdata->user_rating->rating_text; ?> (<?php echo $zomdata->user_rating->aggregate_rating; ?> /5) <br>
                                Cuisines: <?php echo $zomdata->cuisines; echo '<br>' ?>
                                Average cost for two: <?php echo $zomdata->average_cost_for_two; echo '<br>' ?>
							</p>
<!--						</div>-->
                

                  
               
                
                <div class="clearfix"></div>
			         </div>
			             <div class="modal fade" id="myModal5" tabindex="-1" role="dialog">
				            <div class="modal-dialog">
					           <div class="modal-content">
						          <div class="modal-header">
<!--							<button type="button" class="close" data-dismiss="modal">&times;</button>-->
                             
							         <h4>Rate Now!!</h4>
							             <div class="donate_form_w3l">
								            <center><h5>How much will you rate this restaurant?</h5></center>
								                <form action="rate.php" method="GET">  
									               <div class="stars">
                                        <center>

<!--  <form>-->
                                            
    <input class="star star-5" id="star-5" type="radio" name="star" value="5"/>

    <label class="star star-5" for="star-5"></label>

    <input class="star star-4" id="star-4" type="radio" name="star" value="4"/>

    <label class="star star-4" for="star-4"></label>

    <input class="star star-3" id="star-3" type="radio" name="star" value="3"/>

    <label class="star star-3" for="star-3"></label>

    <input class="star star-2" id="star-2" type="radio" name="star" value="2"/>

    <label class="star star-2" for="star-2"></label>

    <input class="star star-1" id="star-1" type="radio" name="star" value="1"/>

    <label class="star star-1" for="star-1"></label>
                                            
    <input type="hidden" name="rid" value="<?php echo $id; ?>">
      
    <input type="submit" name="rate" id="rate" value="RATE">

<!--  </form>-->
                                        </center>
</div>
							
									<div class="clearfix"></div>

                                                    
								</form>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
        
                <div class="col-md-12">
                    <center>
<!--                        <a href="#" class="donate">DELIVERY MENU</a>-->
                        <a href="bookmark.php?restid=<?php echo $id; ?>" class="donate">BOOKMARK</a>
                        <a href="#" class="donate" data-toggle="modal" data-target="#myModal5">BEEN HERE</a>
                        <a href="giveReviews.php?restid=<?php echo $id; ?>" class="donate">REVIEWS</a>
                        <a href="gallery.php" class="donate">PHOTOS</a>
<!--                        <a href="#" class="donate">BOOK A TABLE</a>-->
                    </center>
                </div>
	</div>
	<script type="text/javascript" src="https://components.staticcodes.io/js/jquery-2.1.4.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
     <?php include 'FooterOnly.php';?>

</html>